name: Fleet CI/CD Pipeline

on:
  push:
    branches: ["main"]

jobs:
  build-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      # On force l'utilisation de Node 22 pour l'environnement d'exécution
      - uses: actions/setup-node@v4
        with:
          node-version: '22'
      - run: echo "build-test"

  docker:
    needs: build-test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '22'
      - run: echo "docker build"

  deploy:
    needs: docker
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '22'
      - run: echo "deploy k8s"